# Lesson 6.1 Homework Alex Chen
## Answer the following questions below by writting code in the code cells provided.
___

#### Q1. Complete the following code cell so that the code will output your name, age, and grade.

In [2]:
name = input("Enter your name: ")
## Create a variable for age and grade 
age  = input("Enter your age: ")
grade = input("Enter your grade: ")

print("Your name is", name)
##print the age and grade variables 
print("Your age is", age)
print("Your grade is", grade)
      


Enter your name: alex chen
Enter your age: 18
Enter your grade: 12
Your name is alex chen
Your age is 18
Your grade is 12


#### Q2. Make a markdown cell below that has the following:
- a title heading with your name
- text in bold describing how your day is going
- a horizontal line
- a bullet point list of the programs/schools you have been accepted to so far

- a^2

#### Q3. x is a numpy array definded below. Run the following code cells and add an explaination of each in the markdown cell above.

In [3]:
import numpy as np
x = np.array([[ 1,2,3,4],
 [ 5,6,7,8],
 [ 9,10,11,12],
 [13,14,15,16]])

#### a) 

In [4]:
y = x[:, 2] 
print (y)

[ 3  7 11 15]


#### b) 

In [4]:
y = x[-1,:2] 
print (y)

[13 14]


#### c) 

In [6]:
y = x[:, [True, False, False, True]]
print(y)

[[ 1  4]
 [ 5  8]
 [ 9 12]
 [13 16]]


#### d) 

In [5]:
y = x[0:2, 0:2]
print(y)

[[1 2]
 [5 6]]


#### e)

In [7]:
y = x[:2, :3].reshape((3, 2)) 
print(y)

[[1 2]
 [3 5]
 [6 7]]


#### f)

In [9]:
y=x[:, :2].dot([1, 1]); 
print(y)

[ 3 11 19 27]
