# Lesson 6.2 Homework 

## numPy Practice

Create the following ndarrays:
<br> 1) an ndarray out of the array, arr, given below called A1
<br> 2) a 4 by 4 ndarray made of random numbers from 3 to 15 inclusive
<br> 3) a 3 by 2 ndarray of 1s called A3

In [1]:
import numpy as np
arr = [[5,4,3],[1,2,9]]

## 1)
A1 = np.array(arr)
print(A1)

## 2)
A2 = np.random.randint(3, 16, (4,4))
print(A2)

## 3)
A3 = np.ones((3,2))
print(A3)

[[5 4 3]
 [1 2 9]]
[[ 3  8 14  4]
 [10  8  7 11]
 [14  9 15  4]
 [ 6 14 14 13]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


From A1 above, 
<br> 1) print the number 4
<br> 2) print the second column
<br> 3) print the 1st and 3rd column for the second row

In [2]:
## 1)
print(A1[0,1])

## 2)
print(A1[:,1])

## 3)
print(A1[1,[0,2]])

4
[4 2]
[1 9]


## Pandas Practice

Pick a Data Set from: https://data.ontario.ca/dataset?res_format=CSV
<br> 1) Read in the Data set
<br> 2) Output the First 5 rows
<br> 3) Output the types of each column
<br> 4) Output the mean of one of the numerical columns
<br> 5) Create a new column that is a function of another one

In [9]:
## 1)
import pandas as pd
data = pd.read_csv('https://data.ontario.ca/dataset/c4022f0f-6f3d-4e16-bd28-5312333a4bac/resource/d0d6ccc7-fc60-4a18-ac96-7f9493e9f10e/download/inmatetesting.csv')

In [10]:
## 2)
data.head()

Reported_Date    Region  Cumulative_Number_of_Tests_as_of_Reported_Date  \
0    2020-05-08   Central                                             330   
1    2020-05-08   Eastern                                              84   
2    2020-05-08  Northern                                              72   
3    2020-05-08   Toronto                                             109   
4    2020-05-08   Western                                              82   

   Cumulative_Number_of_Positive_Tests_as_of_Reported_Date  \
0                                                153         
1                                                  1         
2                                                  2         
3                                                  7         
4                                                  0         

   Cumulative_Number_of_Negative_Tests_as_of_Reported_Date  \
0                                                140         
1                                                 76         
2                                                 63         
3                                                 90         
4                                                 62         

   Total_Number_of_Pending_Tests_on_Reported_Date  \
0                                              30   
1                                               7   
2                                               4   
3                                              10   
4                                              17   

   Total_Number_of_Unknown_Tests_on_Reported_Date  \
0                                               7   
1                                               0   
2                                               3   
3                                               2   
4                                               3   

   Total_Inmates_that_Refused_Swab_as_of_Reported_Date  \
0                                                NaN     
1                                                NaN     
2                                                NaN     
3                                                NaN     
4                                                NaN     

   Total_Inmates_on_Medical_Isolation_as_of_Reported_Date  
0                                                222       
1                                                 63       
2                                                  9       
3                                                 70       
4                                                 64

In [11]:
## 3)
data.dtypes

Reported_Date                                               object
Region                                                      object
Cumulative_Number_of_Tests_as_of_Reported_Date               int64
Cumulative_Number_of_Positive_Tests_as_of_Reported_Date      int64
Cumulative_Number_of_Negative_Tests_as_of_Reported_Date      int64
Total_Number_of_Pending_Tests_on_Reported_Date               int64
Total_Number_of_Unknown_Tests_on_Reported_Date               int64
Total_Inmates_that_Refused_Swab_as_of_Reported_Date        float64
Total_Inmates_on_Medical_Isolation_as_of_Reported_Date       int64
dtype: object

In [13]:
## 4)
data["Total_Inmates_on_Medical_Isolation_as_of_Reported_Date"].mean()

74.40966183574879

In [14]:
## 5)
data["Percent_Pos"] = data["Total_Inmates_on_Medical_Isolation_as_of_Reported_Date"]*100
data.tail()

Reported_Date    Region  Cumulative_Number_of_Tests_as_of_Reported_Date  \
1030    2021-03-11   Central                                            6213   
1031    2021-03-11   Eastern                                            6199   
1032    2021-03-11  Northern                                            3877   
1033    2021-03-11   Toronto                                            2899   
1034    2021-03-11   Western                                            5046   

      Cumulative_Number_of_Positive_Tests_as_of_Reported_Date  \
1030                                                503         
1031                                                 40         
1032                                                149         
1033                                                224         
1034                                                165         

      Cumulative_Number_of_Negative_Tests_as_of_Reported_Date  \
1030                                               5469         
1031                                               6023         
1032                                               3596         
1033                                               2553         
1034                                               4568         

      Total_Number_of_Pending_Tests_on_Reported_Date  \
1030                                             137   
1031                                             102   
1032                                              93   
1033                                              91   
1034                                             245   

      Total_Number_of_Unknown_Tests_on_Reported_Date  \
1030                                             104   
1031                                              34   
1032                                              39   
1033                                              31   
1034                                              68   

      Total_Inmates_that_Refused_Swab_as_of_Reported_Date  \
1030                                              940.0     
1031                                             1141.0     
1032                                              799.0     
1033                                             2657.0     
1034                                             1380.0     

      Total_Inmates_on_Medical_Isolation_as_of_Reported_Date  Percent_Pos  
1030                                                284             28400  
1031                                                134             13400  
1032                                                113             11300  
1033                                                 80              8000  
1034                                                340             34000